{{- range $app := .Values.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $app.name }}
  namespace: {{ $app.namespace }}
  {{- if $app.annotations }}
  annotations:
    {{- range $key,$value := $app.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
  - host: {{ $app.host }}
    http:
      paths:
      - path: {{ $app.path }}
        pathType: {{ $app.pathType }}
        backend:
          service:
            name: {{ $app.service }}
            port:
              number: {{ $app.port }}
  ingressClassName: {{ $app.ingressClassName }}
{{- end }}
