---
- name: Deploy Containers
  hosts: localhost
  gather_facts: no
  vars:
    DOCKER_IMAGE_BACKEND: 'my-backend-image'
    DOCKER_IMAGE_WEBSITE: 'my-website-image'
    DOCKER_IMAGE_QR: 'my-qr-image'

  tasks:
    - name: Build Backend
      docker_image:
        name: "{{ DOCKER_IMAGE_BACKEND }}"
        build:
          path: applications/backend
          pull: no
        source: build

    - name: Build Website
      docker_image:
        name: "{{ DOCKER_IMAGE_WEBSITE }}"
        build:
          path: applications/website
          pull: no
        source: build

    - name: Build QR
      docker_image:
        name: "{{ DOCKER_IMAGE_QR }}"
        build:
          path: applications/qr
          pull: no
        source: build

    - name: Deploy containers using docker-compose
      community.docker.docker_compose:
        project_src: /
        state: started




# ---
# - name: Deploy Containers
#   hosts: localhost
#   gather_facts: no
#   vars:
#     DOCKER_IMAGE_BACKEND: 'my-backend-image'
#     DOCKER_IMAGE_WEBSITE: 'my-website-image'
#     DOCKER_IMAGE_QR: 'my-qr-image'

#   tasks:
#     # - name: Build Backend
#     #   shell:
#     #     cmd: docker build -t {{ DOCKER_IMAGE_BACKEND }} applications/backend
#     #   args:
#     #     chdir: "{{ playbook_dir }}"
#     - name: Build Backend
#       docker_image:
#         path: applications/backend
#         name: {{ DOCKER_IMAGE_BACKEND }}
        

#     # - name: Build Website
#     #   shell:
#     #     cmd: docker build -t {{ DOCKER_IMAGE_WEBSITE }} applications/website
#     #   args:
#     #     chdir: "{{ playbook_dir }}"
#     - name: Build Website
#       docker_image:
#         path: applications/website
#         name: {{ DOCKER_IMAGE_WEBSITE }}

#     # - name: Build QR
#     #   shell:
#     #     cmd: docker build -t {{ DOCKER_IMAGE_QR }} applications/qr
#     #   args:
#     #     chdir: "{{ playbook_dir }}"
#     - name: Build Website
#       docker_image:
#         path: applications/website
#         name: {{ DOCKER_IMAGE_QR }}

#     # - name: Deploy Containers
#     #   shell:
#     #     cmd: docker-compose up -d
#     #   args:
#     #     chdir: "{{ playbook_dir }}"
    
#     - name: Deploy containers using docker-compose
#       community.docker.docker_compose:
#         project_src: /
#         state: started
