apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: training-app-backend-prod
type: Opaque
stringData:
  APP_PORT: "3000"
  QR_URL: "http://localhost:8420/"
  MONGO_URI: "mongodb+srv://user:test123@cluster0.qnimcka.mongodb.net"
  MONGO_DB: "Iskander"
