apiVersion: v1
kind: Secret
metadata:
  name: qr-secret
  namespace: training-app-backend-prod
type: Opaque
stringData:
  QR_TMP_FOLDER: "./generated"
  QR_FILL_COLOR: "#121128"
  QR_BACKGROUND_COLOR: "#dcdbdb"
  USE_BUCKET: "false"
  BUCKET_ENDPOINT: ""
  BUCKET_ACCESS_KEY: ""
  BUCKET_SECRET_KEY: ""
  BUCKET_NAME: ""
  BUCKET_PATH: ""
  BUCKET_ENDPOINT_WEB: ""
  