# ---
# - name: Deploy Containers using Role
#   hosts: localhost
#   gather_facts: no

#   roles:
#     - back
#     - qr
#     - front
#     - run 
- name: Deploy Containers using Role
  hosts: localhost
  become: true
  user: root 
  gather_facts: false

  vars:
    qr_role_enabled: "{{ qr }}"
    front_role_enabled: "{{ front }}"
    back_role_enabled: "{{ back }}"
    TEST: "{{ TEST }}"

  roles:
    - { role: back, when: back_role_enabled == 'true' }
    - { role: qr, when: qr_role_enabled == 'true' }
    - { role: front, when: front_role_enabled == 'true' }
    - { role: test, when: TEST == 'true' }
    - run
