namespaces:
  - name: training-app-frontend-prod
  - name: training-app-backend-prod

deployment:
  - app: backend
    namespace: training-app-backend-prod
    replicas: 1
    containers:
      - repository: my-backend-image:latest
        name: backend
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        port: 3000
        env:
          - name: APP_PORT
            secretName: backend-secret
            secretKey: APP_PORT
          - name: QR_URL
            secretName: backend-secret
            secretKey: QR_URL
          - name: MONGO_URI
            secretName: backend-secret
            secretKey: MONGO_URI
          - name: MONGO_DB
            secretName: backend-secret
            secretKey: MONGO_DB
      - repository: my-qr-image:latest
        name: qr
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        port: 8420
        env:
          - name: QR_TMP_FOLDER
            secretName: qr-secret
            secretKey: QR_TMP_FOLDER
          - name: QR_FILL_COLOR
            secretName: qr-secret
            secretKey: QR_FILL_COLOR
          - name: QR_BACKGROUND_COLOR
            secretName: qr-secret
            secretKey: QR_BACKGROUND_COLOR
          - name: USE_BUCKET
            secretName: qr-secret
            secretKey: USE_BUCKET
          - name: BUCKET_ENDPOINT
            secretName: qr-secret
            secretKey: BUCKET_ENDPOINT
          - name: BUCKET_NAME
            secretName: qr-secret
            secretKey: BUCKET_NAME
          - name: BUCKET_ACCESS_KEY
            secretName: qr-secret
            secretKey: BUCKET_ACCESS_KEY
          - name: BUCKET_SECRET_KEY
            secretName: qr-secret
            secretKey: BUCKET_SECRET_KEY
  - app: website
    namespace: training-app-frontend-prod
    replicas: 1
    containers:
      - repository: my-website-image:latest
        name: website
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        port: 4200
    volumeMounts:    
      - name: config-volume
        mountPath: /etc/nginx/html/assets/configs
    volumes:
      - name: config-volume
        configMap:
          name: website-configmap
    configmap:
      - name: website-configmap
        namespace: training-app-frontend-prod
        files: 
          - filename: "app-config.json"
            path: "configs"

secret:
  - name: backend-secret
    namespace: training-app-backend-prod
    stringData: 
      APP_PORT: "3000"
      QR_URL: "http://localhost:8420/"
      MONGO_URI: "mongodb+srv://user:test123@cluster0.qnimcka.mongodb.net"
      MONGO_DB: "Iskander"
  - name: qr-secret
    namespace: training-app-backend-prod
    stringData: 
      QR_TMP_FOLDER: "./generated"
      QR_FILL_COLOR: "#121128"
      QR_BACKGROUND_COLOR: "#dcdbdb"
      USE_BUCKET: "false"
      BUCKET_ENDPOINT: ""
      BUCKET_ACCESS_KEY: ""
      BUCKET_SECRET_KEY: ""
      BUCKET_NAME: ""
      BUCKET_PATH: ""
      BUCKET_ENDPOINT_WEB: ""

service:
  - name: website-service
    namespace: training-app-frontend-prod
    port: 80
    protocol: TCP
    targetPort: 4200
    type: NodePort
    app: website
  - name: backend-service
    namespace: training-app-backend-prod
    port: 8081
    protocol: TCP
    targetPort: 3000
    type: NodePort
    app: backend

ingress:
  - name: backend-ingress
    namespace: training-app-backend-prod
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    host: localhost
    path: /api(/|$)(.*)
    pathType: Prefix
    ingressClassName: nginx
    service: backend-service
    port: 8081
  - name: website-ingress
    namespace: training-app-frontend-prod
    host: localhost
    path: /
    pathType: Prefix
    service: website-service
    port: 80
    ingressClassName: nginx
